### ISSUE TITLE
[iOS] Hotline.unreadCount returns 0 (Cordova/Ionic)

### ISSUE THREAD

**Issue by isharko** [freshdesk/hotline-phonegap#24]
When checking for unreadCount, I keep receiving 0 in the callback. 

Anyone else experiencing this issue?

```
window.Hotline.unreadCount(function(success, val) {
		    //success indicates whether the API call was successful
		    //val contains the no of unread messages
		    console.log("SupportService: Got unread count", success, val);
		    deferred.resolve(val);
});
```
`The unread count value is: 0`

**Comment by rsquare2014** [comment]
Hey can you please check if this issue persists in the latest release(v1.2.0) of the plugin? we did an upgrade to the unreadCount API.

**Comment by isharko** [comment]
Hey, thanks for pushing the update! It seems to be working. The update count is only reflected about a minute after the message is sent, but this will do.

**Comment by hrishikesh-p** [comment]
Hi Ivan @isharko , 

Is push notification configured on the app ? If push notification is not configured, we fallback to polling which is not immediate. There can be delays upto a min or 2 since we throttle unread API calls . 

Can you check with a delay ? But I would recommend implementing push notifications.
